defaults:
  - db: gc
  - schema: default-schema
  - override hydra/launcher: joblib
  - _self_

db_prefix: hshah1
db_name: new_experiment2

args:
  run: ???
  seed: 0
  epoch: 100
  step_size: 1e-3

hydra:
  mode: MULTIRUN
  launcher:
    n_jobs: 2
  sweeper:
    params:
      args.seed: 0,1,2,3
